name: meteo-weather-data
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: meteo-weather-chennai-raw
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
